In [1]:
import numpy as np

In [2]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])
 
for x in np.nditer(A):
    print(x)

1
4
3
5
2
6


In [5]:
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [6]:
np.random.seed(42)
print(np.random.choice(range(1,50),size=6,replace=False))

[14 46 48 45 18 28]


In [11]:
matrix = [0,1,2,3,4,5]
print(np.diag(matrix,0))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [12]:
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [13]:
A = np.arange(12).reshape(-1, 4)
np.save('array.npy', A)
B = np.load('array.npy')
 
 
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
A = np.arange(12, dtype='int').reshape(-1, 4)
np.savetxt(fname='array.txt', X=A, fmt='%0.2f')
B = np.loadtxt('array.txt')

print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [15]:
num = 3415
print(str(num).zfill(8))

00003415


In [18]:
url = (
    'https://e-smartdata.teachable.com/'
    'p/sciezka-data-scientist-machine-learning-engineer'
)

name = url.split('/')[-1]
name = name.replace('-',' ')

print(name)

sciezka data scientist machine learning engineer


In [20]:
subjects = {'mathematics', 'biology', 'physics'}
subjects.add('english')

print(subjects)

{'english', 'mathematics', 'physics', 'biology'}


In [25]:
text = 'Programming in python.'
vowels = {'a', 'e', 'i', 'o', 'u'}

text = text.lower()
text = text.replace(' ', '')
text = text.replace('.', '')

letters = set(text)
consonants = letters.difference(vowels)
 
 
print(f'Number of items: {len(consonants)}')

Number of items: 8


In [27]:
A = {2, 4, 6, 8}
B = {4, 10}

sym_diff = A.symmetric_difference(B)
print(f'Symmetric difference: {sym_diff}')

Symmetric difference: {2, 6, 8, 10}


In [28]:
is_clicked = {'9001', '9002', '9005'}
is_bought = {'9002', '9004', '9005'}

result = is_clicked.intersection(is_bought)
 
print(f'Customer ID: {result}')

Customer ID: {'9005', '9002'}


In [31]:
dji1 = ('AAPL.US', 'IBM.US', 'MSFT.US')
dji2 = ('HD.US', 'GS.US', 'NKE.US')

result = dji1 + dji2

print(result)

('AAPL.US', 'IBM.US', 'MSFT.US', 'HD.US', 'GS.US', 'NKE.US')


In [33]:
ad1_id = {'001', '002', '003'}
ad2_id = {'002', '003', '007'}

result = ad1_id.symmetric_difference(ad2_id)
 
print(f'Selected ID: {result}')

Selected ID: {'001', '007'}
