In [1]:
import numpy as np

In [4]:
np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

print(A)

[[0 0 4 6 2 4 1 1]
 [0 0 6 2 2 4 1 1]
 [0 0 1 3 5 5 1 1]
 [0 0 3 1 5 4 1 1]
 [0 0 2 6 1 3 1 1]]


In [5]:
A1,A2,A3 = np.split(A,[2,6],axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [6]:
np.random.seed(42) 
A = np.random.randint(low=0, high=2, size=(10, 6))

print(np.count_nonzero(A))

31


In [10]:
np.random.seed(42)
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


In [11]:
A = np.array([1.2e-6, 1.7e-7])
 
np.set_printoptions(suppress=True, precision=8)
print(A)

[0.0000012  0.00000017]


In [12]:
np.random.seed(42)
 
A = np.random.randn(8, 4)
print(np.delete(A, [2], axis=1))

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


In [13]:
v = np.array([3, 4, -2])
print(np.linalg.norm(v))

5.385164807134504


In [14]:
np.random.seed(42)
A = np.random.randint(10, size=(100, 30))
 
np.set_printoptions(edgeitems=10)
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]


In [15]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print((A + B) / 2)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


In [16]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(A * B)

[[12 12 18 10]
 [30  9  2 30]]


In [17]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
 
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


In [18]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
 
print(np.allclose(np.power(np.sin(A), 2) + np.power(np.cos(A), 2), B))

True


In [19]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
 
print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))

True


In [20]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
 
print(A.dot(B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


In [21]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
 
print(np.dot(A, B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


In [22]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

print(np.linalg.det(A))

51.999999999999986


In [23]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-0.62616472 -0.89442719  0.89015941]
 [-0.31308236  0.          0.4450797 ]
 [ 0.71407086  0.4472136  -0.09757197]]


In [25]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


In [26]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

print(np.trace(A))

-5


In [27]:
np.random.seed(42)
 
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
 
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]


In [29]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

print(np.argsort(A))

[5 2 1 0 4 3]


In [30]:
np.random.seed(42)
A = np.random.randn(10, 8)
 
print(np.round(A, decimals=3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


In [31]:
W = np.array([4, 5, 1])
 
print(np.roots(W))

[-1.   -0.25]


In [32]:
Q = np.array([2, 4, -5, 1])
R = np.array([2, 0, -5, 1])
 
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


In [33]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


In [34]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
 
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


In [35]:
print(np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]'))

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


In [36]:
A = np.arange('2021-01', '2022-01', dtype='datetime64[M]')
A = A.reshape(-1, 3)
print(A)

[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]


In [37]:
print(np.datetime64('today'))

2024-04-23


In [39]:
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
 
print(np.char.add(A, B))

['001XC' '002YC' '003ZC']


/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/4204645286.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['001', '002', '003'], dtype=np.str)
/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/4204645286.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)


In [40]:
A = np.array(['1', '2', '3'], dtype=np.str)
 
print(np.char.add('000', A))

['0001' '0002' '0003']


/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/3959272687.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['1', '2', '3'], dtype=np.str)


In [41]:
A = np.array(['1', '2', '3'], dtype=np.str)
 
print(np.char.zfill(A, 4))

['0001' '0002' '0003']


/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/1484419278.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['1', '2', '3'], dtype=np.str)


In [42]:
A = np.array(['1', '2', '3'], dtype=np.str)
 
print(np.char.rjust(A, 4, fillchar='0'))

['0001' '0002' '0003']


/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/916709258.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(['1', '2', '3'], dtype=np.str)


In [43]:
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
 
print(np.char.split(A))

[[list(['PLW', 'CDR', '11B', 'TEN']) list(['AMC', 'LPP'])]
 [list(['CDR', 'PKO', 'KGH']) list(['CCC', 'QMK'])]]


/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/3632329703.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)


In [44]:
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
 
print(np.char.strip(np.char.replace(A, '#', ' ')))

[['summer time mood']
 ['sport time']]


In [45]:
A = np.array(
    [
        ['#summer#time#mood', '#vibe'],
        ['#sport#time', '#good#time'],
        ['#event#summer', '#fast#move'],
    ]
)
 
 
print(np.char.count(A, 'time'))

[[1 0]
 [1 1]
 [0 0]]


In [46]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
 
lines = text.splitlines()
lines = [line.split('\t') for line in lines]
result = np.array(lines, dtype=np.str)
print(result)

[['ALIOR' 'PLALIOR00045' '88 860 000' '1 386 216 000' '0,891' '2,16' '14']
 ['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0,831' '5,28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14,702'
  '7,39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4,408' '1,17'
  '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5,733' '9,13'
  '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0,461' '1,51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6,354' '4,78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3,607' '2,91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4,787' '1,43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1,820' '0,42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2,756' '1,16'
  '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6,185' '5,27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2,290' '2,88' '18']
 ['PGNIG' 'PL

/var/folders/g6/368p423d117c1pt_9pkjmw4w0000gn/T/ipykernel_28119/3660076713.py:24: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  result = np.array(lines, dtype=np.str)
