In [1]:
import numpy as np
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [2]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [3]:
A = np.ones(shape=(4,4))
print(np.pad(A, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
A = np.zeros(shape=(6,6),dtype='int')
A[::2,::2] = 10
A[1::2,::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [5]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

print(np.append(A,B,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [6]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])

print(np.intersect1d(A,B))

[0 2 3]


In [7]:
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))

print(np.unique(A))

[1 2 4 5 7 9]


In [8]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

print(np.argmax(A,axis=1))

[0 2 1]


In [9]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [10]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [11]:
print(A[A > 8])

[ 9.99  9.99 14.99]


In [12]:
print(np.where(A > 10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99  4.99]
 [10.    2.39  7.29]]


In [13]:
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99  4.99 14.99  2.39  7.29]


In [14]:
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(np.full_like(A,9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [16]:
print(np.tri(N=5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [17]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
              
              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])
print(A)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]


In [18]:
image = np.random.randint(
    low=0, high=256, size=(200, 300), dtype=np.uint8
)

In [19]:
image = np.random.randint(
    low=0, high=256, size=(200, 300), dtype=np.uint8
)
image_sorted = np.sort(image)

In [20]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])

print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


In [21]:
np.random.seed(42)
 
image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


In [22]:
image = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image_extended = np.expand_dims(image, axis=0)

In [23]:
image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
 
image1 = np.expand_dims(image1, axis=0)
image2 = np.expand_dims(image2, axis=0)
 
images = np.append(image1, image2, axis=0)

In [25]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
print(np.squeeze(A))

[[1 2 3]
 [6 3 2]]


In [26]:
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]]) 
print(np.squeeze(A))

[0.4 0.9 0.5 0.6]


In [27]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [28]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [29]:
np.random.seed(42)
 
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)
print(image[:, :, 0])

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]


In [31]:
image = np.random.randint(
    low=0, high=256, size=(10, 10, 3), dtype=np.uint8
)
result = image[:5, :5, :]
print(result)

[[[162  54 160]
  [186 162 241]
  [ 72 202  32]
  [249 113 197]
  [122  49  32]]

 [[172 166  40]
  [152 169  29]
  [ 27 204  58]
  [234 134  88]
  [244 220 200]]

 [[ 32 204 108]
  [ 24  47  92]
  [ 69  16 246]
  [241 237  94]
  [150 137 156]]

 [[199 186 171]
  [ 74  95 151]
  [103 247  54]
  [163 213  42]
  [ 84  70 218]]

 [[100 186 157]
  [ 30 174  31]
  [194 248 205]
  [ 53 151 182]
  [130 106  82]]]


In [34]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


In [33]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


In [36]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
print(np.column_stack((feature1, feature2, feature3)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]
