In [1]:
import numpy as np

In [2]:
np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']], dtype='<U14')

result = np.char.replace(result, ' ','')
result = np.char.replace(result, ',', '.')
print(result)

[['ALIOR' 'PLALIOR00045' '88860000' '1386216000' '0.891' '2.16' '14']
 ['CCC' 'PLCCC0000016' '27918000' '1292603400' '0.831' '5.28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67348000' '22864646000' '14.702' '7.39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275301000' '6854994900' '4.408' '1.17' '14']
 ['DINOPL' 'PLDINPL00011' '47937000' '8916282000' '5.733' '9.13' '12']
 ['JSW' 'PLJSW0000015' '52636000' '716902320' '0.461' '1.51' '24']
 ['KGHM' 'PLKGHM000017' '136410000' '9881540400' '6.354' '4.78' '8']
 ['LOTOS' 'PLLOTOS00025' '86543000' '5609717260' '3.607' '2.91' '16']
 ['LPP' 'PLLPP0000011' '1306000' '7444200000' '4.787' '1.43' '19']
 ['MBANK' 'PLBRE0000012' '12997000' '2830746600' '1.820' '0.42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647357000' '4285503340' '2.756' '1.16' '13']
 ['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 

In [3]:
np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88860000', '1386216000', '0.891', '2.16', '14'],
       ['CCC', 'PLCCC0000016', '27918000', '1292603400', '0.831', '5.28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67348000', '22864646000', '14.702', '7.39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275301000', '6854994900', '4.408', '1.17', '14'],
       ['DINOPL', 'PLDINPL00011', '47937000', '8916282000', '5.733', '9.13', '12'],
       ['JSW', 'PLJSW0000015', '52636000', '716902320', '0.461', '1.51', '24'],
       ['KGHM', 'PLKGHM000017', '136410000', '9881540400', '6.354', '4.78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86543000', '5609717260', '3.607', '2.91', '16'],
       ['LPP', 'PLLPP0000011', '1306000', '7444200000', '4.787', '1.43', '19'],
       ['MBANK', 'PLBRE0000012', '12997000', '2830746600', '1.820', '0.42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647357000', '4285503340', '2.756', '1.16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6'],
       ['SANPL', 'PLBZ00000044', '33207000', '5213499000', '3.352', '1.91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1043590000', '1252308000', '0.805', '1.21', '33']], dtype='<U12')

stocks_startswith_P = result[np.char.startswith(result[:,0],'P')]
print(stocks_startswith_P)

[['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44' '8']
 ['PKOBP' 'PLPKO0000016' '857593000' '18807014490' '12.093' '10.49' '9']
 ['PLAY' 'LU1642887738' '114151000' '3696209380' '2.377' '1.47' '16']
 ['PZU' 'PLPZU0000011' '568305000' '17515160100' '11.262' '6.64' '6']]


In [4]:
np.set_printoptions(linewidth=150)
stocks_startswith_P = np.array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')

print(np.round(stocks_startswith_P[:,4].astype(float).sum(),2))

49.49


In [5]:
np.set_printoptions(linewidth=160, suppress=True)

wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

lines = wig_games_raw.splitlines()

In [6]:
lines = [line.split('\t') for line in lines]
lines

[['Profile',
  'Time',
  'Course',
  'Change',
  'Change%',
  'Ref.',
  'Open',
  'Low',
  'High',
  'Volume',
  'Turn',
  'Share'],
 ['11B (11BIT)',
  '17 kwi 17:01',
  '391.00',
  '+8.00',
  '(+2.09%)',
  '383.00',
  '383.50',
  '383.00',
  '394.00',
  '12 784',
  '4 994 874',
  '19.034%'],
 ['CDR (CDPROJEKT)',
  '17 kwi 17:01',
  '339.50',
  '+5.30',
  '(+1.59%)',
  '334.20',
  '338.30',
  '337.00',
  '344.20',
  '233 059',
  '79 245 368',
  '39.618%'],
 ['CIG (CIGAMES)',
  '17 kwi 17:03',
  '0.742',
  '-0.012',
  '(-1.59%)',
  '0.754',
  '0.772',
  '0.730',
  '0.772',
  '1 311 078',
  '971 459',
  '1.855%'],
 ['PLW (PLAYWAY)',
  '17 kwi 17:03',
  '387.50',
  '+18.00',
  '(+4.87%)',
  '369.50',
  '374.00',
  '373.00',
  '388.00',
  '33 206',
  '12 661 786',
  '10.638%'],
 ['TEN (TSGAMES)',
  '17 kwi 17:02',
  '349.50',
  '+22.50',
  '(+6.88%)',
  '327.00',
  '332.00',
  '330.00',
  '353.50',
  '39 793',
  '13 697 060',
  '28.855%']]

In [7]:
wig_games = np.array(lines, dtype=str)
wig_games = np.char.replace(wig_games,' ','')
print(wig_games)

[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High' 'Volume' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '+8.00' '(+2.09%)' '383.00' '383.50' '383.00' '394.00' '12784' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '+5.30' '(+1.59%)' '334.20' '338.30' '337.00' '344.20' '233059' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '-0.012' '(-1.59%)' '0.754' '0.772' '0.730' '0.772' '1311078' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '+18.00' '(+4.87%)' '369.50' '374.00' '373.00' '388.00' '33206' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '+22.50' '(+6.88%)' '327.00' '332.00' '330.00' '353.50' '39793' '13697060' '28.855%']]


In [8]:
np.set_printoptions(linewidth=160, suppress=True)
 
wig_games = np.array(
    [
        [
            'Profile',
            'Time',
            'Course',
            'Change',
            'Change%',
            'Ref.',
            'Open',
            'Low',
            'High',
            'Volume',
            'Turn',
            'Share',
        ],
        [
            '11B(11BIT)',
            '17kwi17:01',
            '391.00',
            '+8.00',
            '(+2.09%)',
            '383.00',
            '383.50',
            '383.00',
            '394.00',
            '12784',
            '4994874',
            '19.034%',
        ],
        [
            'CDR(CDPROJEKT)',
            '17kwi17:01',
            '339.50',
            '+5.30',
            '(+1.59%)',
            '334.20',
            '338.30',
            '337.00',
            '344.20',
            '233059',
            '79245368',
            '39.618%',
        ],
        [
            'CIG(CIGAMES)',
            '17kwi17:03',
            '0.742',
            '-0.012',
            '(-1.59%)',
            '0.754',
            '0.772',
            '0.730',
            '0.772',
            '1311078',
            '971459',
            '1.855%',
        ],
        [
            'PLW(PLAYWAY)',
            '17kwi17:03',
            '387.50',
            '+18.00',
            '(+4.87%)',
            '369.50',
            '374.00',
            '373.00',
            '388.00',
            '33206',
            '12661786',
            '10.638%',
        ],
        [
            'TEN(TSGAMES)',
            '17kwi17:02',
            '349.50',
            '+22.50',
            '(+6.88%)',
            '327.00',
            '332.00',
            '330.00',
            '353.50',
            '39793',
            '13697060',
            '28.855%',
        ],
    ],
    dtype='<U14',
)
 
wig_games = np.delete(wig_games, [3, 4, 5, 9], axis=1)
print(wig_games)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [9]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

lines = playway_raw.splitlines()
lines

['Date,Open,High,Low,Close,Volume',
 '2020-03-02,305,324.5,283.5,310,64081',
 '2020-03-03,325.5,340.5,320,340.5,55496',
 '2020-03-04,324,340.5,315,330,36152',
 '2020-03-05,344,344,310,315,35992',
 '2020-03-06,306.5,307,291,305,32539',
 '2020-03-09,274,291,250,258,79402',
 '2020-03-10,278,284.5,256,264,35700',
 '2020-03-11,270,270,238.5,245,60445',
 '2020-03-12,218,228,196,197,94031',
 '2020-03-13,210,229,198.8,211,100412',
 '2020-03-16,205,248,197.8,240.5,50659',
 '2020-03-17,245,269,232.5,264,99480',
 '2020-03-18,264,280,251,270,70136',
 '2020-03-19,267,280,267,279.5,30732',
 '2020-03-20,297.5,307,280,280.5,43426',
 '2020-03-23,274,289,258,285,37098',
 '2020-03-24,305,309,296.5,309,31939',
 '2020-03-25,313,330,295,304,46724',
 '2020-03-26,300,309,295.5,300,27213',
 '2020-03-27,302,306.5,290,296,13466',
 '2020-03-30,299,300,287,300,10316',
 '2020-03-31,302.5,309,302,306.5,15698']

In [10]:
lines = [line.split(',') for line in lines]
lines

[['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
 ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
 ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
 ['2020-03-04', '324', '340.5', '315', '330', '36152'],
 ['2020-03-05', '344', '344', '310', '315', '35992'],
 ['2020-03-06', '306.5', '307', '291', '305', '32539'],
 ['2020-03-09', '274', '291', '250', '258', '79402'],
 ['2020-03-10', '278', '284.5', '256', '264', '35700'],
 ['2020-03-11', '270', '270', '238.5', '245', '60445'],
 ['2020-03-12', '218', '228', '196', '197', '94031'],
 ['2020-03-13', '210', '229', '198.8', '211', '100412'],
 ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
 ['2020-03-17', '245', '269', '232.5', '264', '99480'],
 ['2020-03-18', '264', '280', '251', '270', '70136'],
 ['2020-03-19', '267', '280', '267', '279.5', '30732'],
 ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
 ['2020-03-23', '274', '289', '258', '285', '37098'],
 ['2020-03-24', '305', '309', '296.5', '309', '319

In [14]:
playway = np.array(lines,dtype=str)
print(playway)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

In [15]:
playway = np.array(
    [
        ['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
        ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
        ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
        ['2020-03-04', '324', '340.5', '315', '330', '36152'],
        ['2020-03-05', '344', '344', '310', '315', '35992'],
        ['2020-03-06', '306.5', '307', '291', '305', '32539'],
        ['2020-03-09', '274', '291', '250', '258', '79402'],
        ['2020-03-10', '278', '284.5', '256', '264', '35700'],
        ['2020-03-11', '270', '270', '238.5', '245', '60445'],
        ['2020-03-12', '218', '228', '196', '197', '94031'],
        ['2020-03-13', '210', '229', '198.8', '211', '100412'],
        ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
        ['2020-03-17', '245', '269', '232.5', '264', '99480'],
        ['2020-03-18', '264', '280', '251', '270', '70136'],
        ['2020-03-19', '267', '280', '267', '279.5', '30732'],
        ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
        ['2020-03-23', '274', '289', '258', '285', '37098'],
        ['2020-03-24', '305', '309', '296.5', '309', '31939'],
        ['2020-03-25', '313', '330', '295', '304', '46724'],
        ['2020-03-26', '300', '309', '295.5', '300', '27213'],
        ['2020-03-27', '302', '306.5', '290', '296', '13466'],
        ['2020-03-30', '299', '300', '287', '300', '10316'],
        ['2020-03-31', '302.5', '309', '302', '306.5', '15698'],
    ],
    dtype='<U10',
)

In [16]:
playway = np.delete(playway,[0], axis=1)
playway_values = playway[1:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

In [18]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)
print(np.round(playway_values.mean(axis=0),2))

[  283.14   295.25   268.69   282.3  48688.05]


In [20]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

In [21]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)
 
print(playway_values[playway_values[:, 3] > 300.0])

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


In [23]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)
 
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


In [25]:
np.set_printoptions(suppress=True)
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)
 
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 